# Generated by Django 4.1.1 on 2022-09-18 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='info',
            new_name='DocInfos',
        ),
    ]
