# Generated by Django 4.1.1 on 2022-10-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_info_docinfos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docinfos',
            old_name='input1',
            new_name='allYearResidents',
        ),
        migrations.RenameField(
            model_name='docinfos',
            old_name='input2',
            new_name='busyRotations',
        ),
        migrations.AddField(
            model_name='docinfos',
            name='block',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docinfos',
            name='impossibleAssignments',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docinfos',
            name='mustDo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docinfos',
            name='partialYearResidents',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docinfos',
            name='people',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docinfos',
            name='preference',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docinfos',
            name='rotations',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docinfos',
            name='vacation',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
